# Generated by Django 4.2.21 on 2025-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diaryentry_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
