# Generated by Django 4.2.21 on 2025-05-29 06:37

import apps.todos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_description_alter_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    apps.todos.validators.MaxLengthExclusiveValidator(
                        10, message="descriptionは10文字未満で入力してください。"
                    )
                ],
                verbose_name="詳細",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    apps.todos.validators.MinLengthExclusiveValidator(
                        10, message="Titleは10文字以上で入力してください。"
                    )
                ],
                verbose_name="タイトル",
            ),
        ),
    ]
