# Generated by Django 4.2.21 on 2025-05-30 05:13

import apps.todos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_description_alter_todo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    apps.todos.validators.MaxLengthExclusiveValidator(
                        30, message="descriptionは30文字未満で入力してください。"
                    )
                ],
                verbose_name="詳細",
            ),
        ),
    ]
